name: Run tests

on: [pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
      - name: Change wrapper permission
        run: chmod +x ./gradlew
      - name: Test
        run: ./gradlew clean allTests

  artifact:
    name: Publish - Nexus
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
      - name: Change wrapper permission
        run: chmod +x ./gradlew
      - name: Release NPM package
        run: ./gradlew publishJsPackageToNpmjsRegistry
        env:
          NPMJS_TOKEN: ${{ secrets.DHIS2_BOT_NPM_TOKEN }}
      - name: Release Maven package
        if: false
        run: ./gradlew publishAllPublicationsToSonatypeRepository
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_OSSRH_PASSWORD }}
