name: Run tests

on:
  push:
    branches:
      - 'main'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Change wrapper permission
        run: chmod +x ./gradlew
      - name: Test
        run: ./gradlew clean allTests
  publish:
    name: Publish - Nexus
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - name: Change wrapper permission
        run: chmod +x ./gradlew
      - name: Release Maven package
        run: ./gradlew publishAllPublicationsToSonatypeRepository
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_OSSRH_PASSWORD }}
