name: Merge to Main

on:
  push:
    branches:
      - 'main'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Test
        run: ./gradlew clean test

  artifact:
    name: Publish - Nexus
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Release Maven package
        run: ./gradlew publishJvmPublicationToSonatypeRepository -PremoveSnapshot
        with:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_OSSRH_PASSWORD }}
          SIGNING_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}
