name: Pull request

on: [pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'gradle'
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - name: Pack
        run: ./gradlew clean packJsPackage
      - name: Publish beta to NPMJS
        run:
          chmod +x ./scripts/publish-beta.sh
          ./scripts/publish-beta.sh

